### ISSUE TITLE
Template refer to deleted mock

### ISSUE THREAD

**Issue by hori-ryota** [suzujun/gendao#5]
Mock template was deleted but even now is used.

[Deleted mock tamplate · suzujun/gendao@b6dd681](https://github.com/suzujun/gendao/commit/b6dd6817ff4bda48b39cae40326c48c595fa2add)

[gendao/dao\_xxx\_gen\.tpl at master · suzujun/gendao](https://github.com/suzujun/gendao/blob/master/template/dao_xxx_gen.tpl#L127)

**Comment by suzujun** [comment]
merged
